import { useEffect, useState } from "react";
import { api, type NarrativeResponse } from "../lib/api";

export default function Narrative({ stateCode }: { stateCode: string }) {
  const [data, setData] = useState<NarrativeResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setData(null);
    setError(null);
    api.getNarrative(stateCode)
      .then((r) => setData(r.data))
      .catch((e) => setError(e?.message || "Could not load narrative."));
  }, [stateCode]);

  if (error) return <p className="text-sm text-red-600">{error}</p>;
  if (!data) {
    return (
      <div className="rounded-xl border border-ink-200 bg-white p-5">
        <h3 className="font-display font-semibold text-base">What this region's profile could help foster</h3>
        <p className="text-xs text-ink-500 mt-1 mb-3">Generated by Gemini from public Wikipedia listings, NOAA climate normals, and US Census data.</p>
        <p className="text-sm text-ink-500 animate-pulse">Generating narrative...</p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-ink-200 bg-white p-5 space-y-3">
      <div className="flex items-baseline justify-between">
        <h3 className="font-display font-semibold text-base">What this region's profile could help foster</h3>
        <span className="text-xs text-ink-500">
          {data.cache_hit ? "cached" : "generated"} • {data.model}
        </span>
      </div>
      <p className="text-xs text-ink-500">Generated by Gemini from public Wikipedia listings, NOAA climate normals, and US Census data. Conditional phrasing throughout.</p>
      {data.narrative.split(/\n\n+/).map((para, i) => (
        <p key={i} className="text-sm leading-relaxed">{para}</p>
      ))}
    </div>
  );
}
